PROGS_SANDGLASS_OBJS := sandglass.o
PROGS_SANDGLASS_OBJS := $(PROGS_SANDGLASS_OBJS:%=$(TDIR)/sandglass/%)
ALL_OBJS += $(PROGS_SANDGLASS_OBJS)

$(TDIR)/bin/sandglass : $(TSTART) $(PROGS_SANDGLASS_OBJS) $(TLIBC)

